### ISSUE TITLE
Assignment #1 is ready for Grading

### ISSUE THREAD

**Issue by sivilyslare** [SES-5215-F2020/cschmidt-quant#1]
.Rmd, .html, .csv files are all ready

**Comment by saratepfer** [comment]
Thank you, Christian. Nice job on this. Your unit of analysis, number of observations, and who's included in your sample population are all clearly stated.

**Comments on Code**
Line 13: To avoid cluttering your output with package messages, consider replacing this line with ```{r load libraries, message=FALSE}
