### ISSUE TITLE
Assignment 3 is complete! Thanks for looking it over.

### ISSUE THREAD

**Issue by sivilyslare** [SES-5215-F2020/cschmidt-quant#3]
https://ses-5215-f2020.github.io/cschmidt-quant_assignment3.html

**Comment by saratepfer** [comment]
Thank you, Christian. This looks good. Please see a few comments below.

- line 13: replace {r} with {r, message = FALSE} to prevent unnecessary messages from printing in the knitted html.
- if you want lines 22-26 and 29-32 to print on their own lines, then end each line with a double space.
- if you would like to remove the scientific notation from your salary/weekly hours worked plot, then add the following line above the ggplot lines: options(scipen = 999)
- I would add to your interpretation of the Pearson's correlation what you think the strength of the correlation is.
- It would be great to see some visualizations of the two-sample t-test. 
- Please include an additional return between your code chunks and your interpretations/observations. This allows the interpretation/observation to be on its own line and makes your code easier to read.
